# Generated by Django 6.0.6 on 2026-07-06 18:20

import django.db.models.deletion
import ledger.models.upload_sessions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('holder_type', models.CharField(choices=[('user', 'User'), ('collective', 'Collective'), ('external', 'External')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=ledger.models.upload_sessions.UploadSession.receipt_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('acquisition_year', models.PositiveSmallIntegerField(default=2026)),
                ('depreciation_years', models.PositiveSmallIntegerField(default=5, help_text='Normally 5 years according to German GWG Sammelposten.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_pools', to='ledger.accountholder')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('receipt', 'Receipt'), ('event', 'Event')], max_length=20)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ledger.accountholder')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ledger.category')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ledger.category')),
                ('collective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ledger.accountholder')),
                ('responsible_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_events', to='ledger.accountholder')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account')], default='cash', max_length=20)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_accounts', to='ledger.accountholder')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('finance_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='ledger.financeaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('in', 'Ingoing (money received)'), ('out', 'Outgoing (money spent)'), ('intern', 'Internal Transfer')], default='out', max_length=10)),
                ('tax_category', models.CharField(blank=True, choices=[('ideel', 'Ideeler Bereich'), ('vermoegen', 'Vermögensverwaltung'), ('zweck', 'Zweckbereich'), ('wirtschaftlich', 'Wirtschaftlicher Bereich')], max_length=20, null=True)),
                ('address_status', models.CharField(choices=[('ok', 'ok'), ('incorrect', 'incorrect')], default='ok', max_length=10)),
                ('document_status', models.CharField(choices=[('attached', 'Attached'), ('pending', 'Missing receipt'), ('no', 'No receipt')], default='no')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='ledger.category')),
                ('collective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collective_receipts', to='ledger.accountholder')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_receipts', to='ledger.accountholder')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='ledger.event')),
                ('responsible_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_receipts', to='ledger.accountholder')),
                ('uploaded_by_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipts', to='ledger.accountholder')),
                ('upload_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt', to='ledger.uploadsession')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('useful_life', models.PositiveSmallIntegerField(default=3, help_text='Useful life in years according to AfA table.')),
                ('depreciation_method', models.CharField(choices=[('linear', 'Linear'), ('none', 'Immediate Expense')], default='linear', max_length=20)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=Decimal('33.33'), help_text='Annual depreciation percentage.', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ledger.accountholder')),
                ('asset_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='ledger.assetpool')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='ledger.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('created_by_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to='ledger.accountholder')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ledger.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='AccountHolderMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ledger.accountholder')),
                ('django_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('django_user', 'account_holder')},
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='ledger.financeaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['account'], name='ledger_tran_account_8285b6_idx'), models.Index(fields=['transaction'], name='ledger_tran_transac_3640f6_idx')],
            },
        ),
    ]
